#!/usr/bin/perl
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
# allow_client_access - script to update the default redhat 7.1
#                       security installation to allow client 
#                       access to this server machine
#
# $Id$
#
# Author: Neil Gorsuch

use SystemInstaller::Machine;

$IPCHAINS = "/etc/sysconfig/ipchains";
$IPCHAINS_BKUP = "/etc/sysconfig/ipchains.bak";

# Use Schwartzian transform to sort node names alphabetically and numerically.
# Names w/o numeric suffix preceed those with numeric suffix.
sub sortnodes(@) {
	return map { $_->[0] }
	       sort { $a->[1] cmp $b->[1] || ($a->[2]||-1) <=> ($b->[2]||-1) }
	       map { [$_, /^([\D]+)([\d]*)$/] }
	       @_;
}

# find the names of the oscar client machines defined so far
my %machines = get_machine_listing();
my @clients = ();
foreach my $client_key (sortnodes( keys %machines )) {
    my $client_ref = $machines{$client_key};
    my $host = $$client_ref{HOST};
    push @clients, $host 
	if $host !~ /^\s*$/;
}

# see if ipchains is installed on the system
if (! -r "/etc/init.d/ipchains") {
	print "No ipchains on this computer\n";
	print "No modification to do for ipchains\n";
	exit(0);
}

# see if we are running ipchains
if ( scalar ( @ipchains_cmd_out = `/etc/init.d/ipchains status 2>/dev/null` ) ) {
    print "It looks like this system is running the ipchains \"service\" from Redhat.\n";
    print "Examining $IPCHAINS ...\n";

    # read in the ipchains configuration file and initialize the changed file
    if (open(INFILE, "<$IPCHAINS")) {
	@ipchains_in = ( <INFILE> ) ;
	close(INFILE);
	chomp @ipchains_in;
    } else {
	@ipchains_in = ();
    }
    
    @ipchains_out = @ipchains_in;

    $ipchains_changed = 0;

    # figure out which oscar clients are needed
    @clients_needed = ();
    foreach $client ( @clients ) {
	if ( ! grep ( /^-A input -s $client /, @ipchains_out ) ) {
	    push @clients_needed, $client;
	}
    }
    if ( ! @clients_needed ) {
	print "Congratulations, no changes are needed to allow client access.\n";
    } else {
	print "We need to add rules to allow these clients access:\n";
	foreach $client ( @clients_needed ) {
	    print "$client\n";
	}
	@ipchains_new = ();
	$inserted = 0;
	foreach $line ( @ipchains_out ) {
	    if ( ! $inserted && grep ( /^-A /, $line ) ) {
		foreach $client ( @clients_needed ) {
#		    push @ipchains_new, "#following line added by OSCAR to allow client $client access";
		    push @ipchains_new, "-A input -s $client -d 0/0 -j ACCEPT";
		}
		$inserted = 1;
	    }
	    push @ipchains_new, $line;
	}
	if ( ! $inserted ) {
	    foreach $client ( @clients ) {
#		push @ipchains_new, "#following line added by OSCAR to allow client $client access";
		push @ipchains_new, "-A input -s $client -d 0/0 -j ACCEPT";
	    }
	}
	@ipchains_out = @ipchains_new;
	$ipchains_changed = 1;
    }

    # see if we already have lines enabling bootp loading
    $line1 = "-A\ input\ -s\ 0/0\ 68\ -d\ 255.255.255.255\ 67\ -p\ udp\ -j\ ACCEPT";
    $line2 = "-A\ input\ -s\ 0/0\ 67\ -d\ 255.255.255.255\ 68\ -p\ udp\ -j\ ACCEPT";
    if ( ( grep ( /^$line1/, @ipchains_out ) ) &&
	 ( grep ( /^$line2/, @ipchains_out ) ) ) {
	print "Congratulations, the lines are already there to allow client net booting.\n";
    } else {
	print "We need to add lines to allow client net booting.\n";
	@ipchains_new = ();
	$inserted = 0;
	foreach $line ( @ipchains_out ) {
	    if ( ! $inserted && grep ( /^-A input/, $line ) ) {
#		push @ipchains_new, "\# following line added by OSCAR to allow client installations:";
		push @ipchains_new, $line1
		    if ( ! grep ( /^$line1\$/, @ipchains_out ) );
		push @ipchains_new, $line2
		    if ( ! grep ( /^$line2\$/, @ipchains_out ) );
		$inserted = 1;
	    }
	    push @ipchains_new, $line;
	}
	if ( ! $inserted ) {
#	    push @ipchains_new, "# following line added by OSCAR to allow client installations:";
	    push @ipchains_new, $line1
		if ( ! grep ( /^$line1\$/, @ipchains_out ) );
	    push @ipchains_new, $line2
		if ( ! grep ( /^$line2\$/, @ipchains_out ) );
	}
	@ipchains_out = @ipchains_new;
	$ipchains_changed = 1;
    }

    # if the file changed, save a copy and write out the new one
    if ( ! $ipchains_changed ) {
	print "No changes have been made.\n";
    } else {
#	if ( scalar ( @ipchains_in ) ) {
#	    print "Here is what the old $IPCHAINS looked like:\n";
#	    print "=======================================================================\n";
#	    for $line ( @ipchains_in ) { print "$line\n"; };
#	    print "=======================================================================\n";
#	}
#	print "Here is what the new $IPCHAINS looks like:\n";
#	print "=======================================================================\n";
#	for $line ( @ipchains_out ) { print "$line\n"; };
#	print "=======================================================================\n";
	if ( scalar ( @ipchains_in ) ) {
	    print "cp -p $IPCHAINS $IPCHAINS_BKUP\n";
	    die "cannot make a backup copy $IPCHAINS_BKUP of $IPCHAINS\n"
		if ( system "cp -p $IPCHAINS $IPCHAINS_BKUP" );
	}
	print "Writing out modified $IPCHAINS file.\n";
	open(OUTFILE, ">$IPCHAINS") or die "Could not write $IPCHAINS\n";
	foreach $line ( @ipchains_out ) { print OUTFILE "$line\n" };
	close(OUTFILE);
	
	print "Restarting ipchains packet filtering to catch new rules\n";
	print "/etc/init.d/ipchains restart\n";
	`/etc/init.d/ipchains restart`;
    }
}



exit(0);
