#!/usr/bin/perl
#
# Copyright (c) 2008 Geoffroy Vallee <valleegr@ornl.gov>
#                    Oak Ridge National Laboratory
#                    All rights reserved.
#

BEGIN {
    if (defined $ENV{OSCAR_HOME}) {
        unshift @INC, "$ENV{OSCAR_HOME}/lib";
    }
}

use strict;
use OSCAR::ImageMgt;
use File::Copy;
use Carp;

print "\n\n*** OSCAR::ImageMgt Testing ***\n\n";

my $basedir;
if (defined $ENV{OSCAR_HOME}) {
    $basedir = "$ENV{OSCAR_HOME}/testing/unit_testing";
} else {
    $basedir = "/usr/share/oscar/testing/unit_testing";
}

my $orig_file = "$basedir/samples/systemconfig.conf.tmpl";
if (! -f $orig_file) {
    die "ERROR: Impossible to find the $orig_file file";
}

my $test_file = "/tmp/systemconfig.conf";

unlink ($test_file) if (-f $test_file);
File::Copy::copy($orig_file, $test_file) or die "ERROR: File cannot be copied.";

if (OSCAR::ImageMgt::update_systemconfigurator_configfile ($test_file) == -1) {
    die "ERROR: Impossible to update the SystemConfigurator configuration file";
}

print "*** SUCCESS: OSCAR::ImageMgt Testing ***\n\n";
