#!/usr/bin/perl
#
# Copyright (c) 2008 Geoffroy Vallee <valleegr@ornl.gov>
#                    Oak Ridge National Laboratory
#                    All rights reserved.
#

use strict;
use lib "$ENV{OSCAR_HOME}/lib";
use OSCAR::SystemInfo;
use Carp;

my $info = OSCAR::SystemInfo->new();
$info->proc_info ();
$info->cache_info ();