#!/usr/bin/perl
#

use strict;
use lib "$ENV{OSCAR_HOME}/lib";
use OSCAR::PackageSmart;

print "Test the detection of repositories formats. This detection is " .
      "based on the repository URL. We submit few cases and check the result\n";

my $pool;

$pool = "/tftpboot/distro/debian-4-x86_64";
print "Testing $pool\n";
my $format = 
    OSCAR::PackageSmart::detect_pool_format ($pool);
goto ERROR_EXIT if ($format ne "deb");

$pool = "/tftpboot/oscar/debian-4-x86_64";
print "Testing $pool\n";
my $format = 
    OSCAR::PackageSmart::detect_pool_format ($pool);
goto ERROR_EXIT if ($format ne "deb");

$pool = "/tftpboot/oscar/common-rpms";
print "Testing $pool\n";
my $format = 
    OSCAR::PackageSmart::detect_pool_format ($pool);
goto ERROR_EXIT if ($format ne "rpm");

$pool = "file:/tftpboot/oscar/common-debs";
print "Testing $pool\n";
my $format = 
    OSCAR::PackageSmart::detect_pool_format ($pool);
goto ERROR_EXIT if ($format ne "deb");

$pool = "/tftpboot/oscar/common-debs";
print "Testing $pool\n";
my $format = 
    OSCAR::PackageSmart::detect_pool_format ($pool);
goto ERROR_EXIT if ($format ne "deb");

$pool = "/tftpboot/distro/redhat-el-ws-4-i386";
print "Testing $pool\n";
my $format = 
    OSCAR::PackageSmart::detect_pool_format ($pool);
goto ERROR_EXIT if ($format ne "rpm");

$pool = "/tftpboot/distro/redhat-el-ws-4-i386.url";
print "Testing $pool\n";
my $format = 
    OSCAR::PackageSmart::detect_pool_format ($pool);
goto ERROR_EXIT if ($format ne "rpm");

$pool = "/tftpboot/oscar/rhel-4-i386";
print "Testing $pool\n";
my $format =
    OSCAR::PackageSmart::detect_pool_format ($pool);
    print "Format: $format\n";
    goto ERROR_EXIT if ($format ne "rpm");

$pool = "/tftpboot/oscar/debian-4-i386";
print "Testing $pool\n";
my $format =
    OSCAR::PackageSmart::detect_pool_format ($pool);
goto ERROR_EXIT if ($format ne "deb");

print "The following test should generate an error...\n";

$pool = "/tftpboot/oscar/toutou-5-x86_64";
print "Testing $pool\n";
my $format = 
    OSCAR::PackageSmart::detect_pool_format ($pool);
goto ERROR_EXIT if (defined ($format));

print "The following test should generate an error...\n";
print "Testing $pool\n";
$pool = "/tftpboot/oscar/centos-x86_64";
my $format = 
    OSCAR::PackageSmart::detect_pool_format ($pool);
goto ERROR_EXIT if (defined ($format));

print "The following test should generate an error...\n";
print "Testing $pool\n";
$pool = "/tftpboot/oscar/toutou-5-titi";
my $format = 
    OSCAR::PackageSmart::detect_pool_format ($pool);
goto ERROR_EXIT if (defined ($format));

print "The following test should generate an error...\n";
$pool = "/tftpboot/oscar/centos-5-x86_64.url";
print "Testing $pool\n";
my $format = 
    OSCAR::PackageSmart::detect_pool_format ($pool);
goto ERROR_EXIT if (defined ($format));


print "\n\nSUCCESS: the test of repository pool format detection succeed\n";

exit 0;

ERROR_EXIT:
    print "ERROR: the test of repository pool format detection failed\n";
    exit -1;
