#!/usr/bin/perl
#

use strict;
use lib "$ENV{OSCAR_HOME}/lib";
use OSCAR::Prereqs;
use OSCAR::Utils;
use OSCAR::ConfigManager;
use warnings "all";

print "\n\n*** Testing the OSCAR prereq mechanism ***\n\n";

print "\t-> Prereqs testing simulating Debian 4 x86_64\n";

print "\t*********************************************************\n";
print "\t-> Raw list of prereqs (i.e., not checking packages status)\n";

my $config_file = "/etc/oscar/oscar.conf";
my $oscar_cfg = OSCAR::ConfigManager->new(config_file => "$config_file");
my $config = $oscar_cfg->get_config();
my $path = $config->{'prereqs_path'};

my ($installs, $removes, $cmds) = 
    OSCAR::Prereqs::get_rawlist_prereqs("debian",
                                    4,
                                    "x86_64",
                                    "$path/base/");

print "\t-> Prereqs: packages to install: ";
print_array (@$installs);

print "\t-> Prereqs: packages to remove: ";
print_array (@$removes);

print "\t-> Prereqs: commands to execute: ";
print_array (@$cmds);

print "\t*********************************************************\n";
print "\t-> Prereqs status\n";

OSCAR::Prereqs::get_prereqs_status("debian",
                                   4,
                                   "x86_64",
                                    "$path/base/");

my $ret = OSCAR::Prereqs::check_installed(@$installs);
print "\t-> Number of packages to install: $ret\n";

$ret = OSCAR::Prereqs::check_removed(@$removes);
print "\t-> Number of packages to remove: $ret\n";


print "\t*********************************************************\n";
print "\t-> List of actions needed for prereqs\n";

($installs, $removes, $cmds) = 
    OSCAR::Prereqs::get_prereqs("debian",
                                    4,
                                    "x86_64",
                                    "$path/base/");

print "\t-> Prereqs: packages to install: ";
print_array (@$installs);

print "\t-> Prereqs: packages to remove: ";
print_array (@$removes);

print "\t-> Prereqs: commands to execute: ";
print_array (@$cmds);

print "*** SUCCESS: Testing the OSCAR prereq mechanism ***\n\n";
