#!/usr/bin/perl
#
# Copyright (c) 2007 Oak Ridge National Laboratory.
#                    Geoffroy R. Vallee <valleegr@ornl.gov>
#                    All rights reserved.

use strict;
use lib "$ENV{OSCAR_HOME}/lib";
use OSCAR::PackageSmart;
use OSCAR::PackagePath;
use Cwd;

print "Test few repository related functions.\n";

my $path = getcwd() . "/samples/empty_repo";
if (OSCAR::PackagePath::repo_local ($path) != 1) {
    print "ERROR: the fake repo $path is detected as not local";
    goto ERROR_EXIT;
}
if (OSCAR::PackagePath::repo_empty ($path) != 1) {
    print "ERROR: the fake repo $path is detected as not empty";
    goto ERROR_EXIT;
}

print "Test the preparation of pools.\n";

my $fake_pool = "/tftpboot/oscar/rhel-4-x86_64";
my $yume_cmd = "/usr/bin/yume";
if (! -f $yume_cmd) {
    print "For testing we need to use yume\n";
    goto ERROR_EXIT;
}

if (! -d  $fake_pool) {
    print "For testing we need a \"fake\" pool which is $fake_pool. This pool ".
          "can be empty or not, this test should not impact the status of the ".
          "pool. Please create this directory.\n";
    goto ERROR_EXIT;
}

my $pm = 
    OSCAR::PackageSmart::prepare_pool (1, $fake_pool);
goto ERROR_EXIT if (!defined($pm));


print "\n\nSUCCESS: the test of repository preparation succeed\n";

exit 0;

ERROR_EXIT:
    print "ERROR: the test of repository preparation failed\n";
    exit -1;
