#!/usr/bin/perl
#
# Copyright (c) 2008 Geoffroy Vallee <valleegr@ornl.gov>
#                    Oak Ridge National Laboratory
#                    All rights reserved.
#

BEGIN {
    if (defined $ENV{OSCAR_HOME}) {
        unshift @INC, "$ENV{OSCAR_HOME}/lib";
    }
}

use strict;
use OSCAR::SystemInfo;
use Carp;

print "\n\n*** OSCAR::SystemInfo Testing ***\n\n";

my $info = OSCAR::SystemInfo->new();
$info->proc_info ();
$info->cache_info ();

print "*** SUCCESS: OSCAR::SystemInfo Testing ***\n\n";
