#!/usr/bin/perl
#
# Copyright (c) 2007 Oak Ridge National Laboratory.
#                    Geoffroy R. Vallee <valleegr@ornl.gov>
#                    All rights reserved.

BEGIN {
    if (defined $ENV{OSCAR_HOME}) {
        unshift @INC, "$ENV{OSCAR_HOME}/lib";
    }
}

use strict;
use OSCAR::ConfigManager;

print "\n\n*** Test few oscar-config capabilities ***\n\n";

my $path = "/etc/oscar/oscar.conf";
my $oscar_cfg = OSCAR::ConfigManager->new(config_file => "$path");
my $config = $oscar_cfg->get_config();
my $path = $config->{'binaries_path'};
my $script = "$path/oscar-config";

my $cmd = $script . " --help";
print "Executing: $cmd\n";
if (system ($cmd)) {
    goto ERROR_EXIT;
}

my $cmd = $script . " --supported-distros";
print "Executing: $cmd\n";
goto ERROR_EXIT if (system ($cmd));

my $list_distros = `$cmd`;
goto ERROR_EXIT if ($list_distros eq "");


print "\n\n*** SUCCESS: the test of oscar-config succeed ***\n\n";

exit 0;

ERROR_EXIT:
    print "ERROR: the test of oscar-config failed\n";
    exit -1;
