# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OSCAR
email: oscar-users@lists.sourceforge.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/oscar" # the subpath of your site, e.g. /blog
url: "https://oscar-cluster.github.io" # the base hostname & protocol for your site
twitter_username: potatoid
github_username:  dikim33

# Build settings
markdown: kramdown
#markdown: redcarpet
#redcarpet:
#      extensions: ["tables", "fenced_code_blocks"]

#theme: sinatra
remote_theme: jekyll-theme-slate

# Wikis
include: ['_wikis']
