#!/bin/bash
#
# Copyright (c) 2004 The Trustees of Indiana University.
#                         All rights reserved.
#
# This file is part of the OSCAR software package.  For license
# information, see the COPYING file in the top level directory of the
# OSCAR source distribution.
#
# $Id: setup,v 1.4 2004/04/07 04:35:06 tuelusr Exp $
#
# setup script for the packman-depman package
#

VERSION=1.3
# Mat Garrett, <magarret@OSL.IU.edu>
# Moved PackMan/DepMan out of .../lib/OSCAR into an RPM
VERSION=1.4
# Mat Garrett, <magarret@OSL.IU.edu>
# Now installs not only in the default /opt/oscar, but also the current
# build directory

VERSION=$(echo "$Revision: 1.4 $" | cut --fields 2 --delimiter " ")

PACKAGE=packman-depman
if [[ $0 = */* ]] ; then
  MEDIA_DIR=${0%/*}/../RPMS
else
  MEDIA_DIR=${0%/*/*}/RPMS
fi

CURRENT=$(ls -1 --sort=version --reverse "${MEDIA_DIR}/${PACKAGE}"-*.noarch.rpm |
	head -1)

echo "Installing ${CURRENT##*/} in the build directory"
rpm --upgrade --force --relocate "/opt/oscar=$OSCAR_HOME" "${CURRENT}"
echo "Installing ${CURRENT##*/} in its permanent home"
rpm --upgrade --force "${CURRENT}"
echo "Done."
