#!/bin/bash
#
# Copyright (c) 2003 The Trustees of Indiana University.
#                         All rights reserved.
#
# This file is part of the OSCAR software package.  For license
# information, see the COPYING file in the top level directory of the
# OSCAR source distribution.
#
# $Id: setup,v 1.2 2004/04/06 14:52:56 tuelusr Exp $
#
# setup script for the packman-depman package
#

VERSION=1.3
# Mat Garrett, <magarret@OSL.IU.edu>
# Moved PackMan/DepMan out of .../lib/OSCAR into an RPM

VERSION=$(echo "$Revision: 1.2 $" | cut --fields 2 --delimiter " ")

PACKAGE=packman-depman
if [[ $0 = */* ]] ; then
  echo foo
  MEDIA_DIR=${0%/*}/../RPMS
else
  echo bar
  MEDIA_DIR=${0%/*/*}/RPMS
fi

CURRENT=$(ls -1 --sort=version --reverse "${MEDIA_DIR}/${PACKAGE}"-*.noarch.rpm |
	head -1)

echo "Installing ${CURRENT##*/}"
rpm --upgrade "${CURRENT}"

echo "Done."
