#!/bin/bash
# $Id$
#
# Copyright (c) 2013 CEA² Commissariat à l'Energie Atomique et aux Energies Alternatives
#                    Olivier LAHAYE <olivier.lahaye@cea.fr>
#                    All rights reserved
#
# This script compute the end of the oscar repository URL taking into account
# The distro, the distro version, the oscar version.
# Syntax: $0 <URL base>
# example: compute_repo_url http://www.usablesecurity.net/OSCAR/repos
#          compute_repo_url http://svn.oscar.openclustergroup.org/repos
#          compute_repo_url https://olivier.lahaye1.free.fr/OSCAR/repos

# Make sure OSCAR_VERBOSE won't interfer if set by oscar-packager
export OSCAR_VERBOSE=0

if test -n "$1"
then
    URL_BASE="$1"
else
    URL_BASE="https://olivier.lahaye1.free.fr/OSCAR/repos"
fi

#if test -z $(echo $URL_BASE |grep -E '(ht|f)tp://[a-zA-Z0-9\-\./]+$')
# OL : We don't want to enforce full URL as sometimes we only need the end of the URL
if test "$URL_BASE" = "--help"
then
	echo "Usage: $0 [URL BASE]"
	exit 0
fi

if [ -z "$OSCAR_HOME" ]
then
    OSCAR_HOME=`pwd`/..
fi

export OSCAR_HOME # distro-query need it.

source ${OSCAR_HOME}/VERSION

OSCAR_VERSION=""
if test "$want_build_r" -eq 1
	then
		OSCAR_VERSION="unstable"
	else
		OSCAR_VERSION="$major.$minor.$release"
fi

ARCH=$(arch)
if test -n ""$(echo "#i486#i586#i686#"|grep "#${ARCH}#")
then
	ARCH="i386"
fi

DISTRO_QUERY=""
for P in ${OSCAR_HOME}/utils /usr/bin
do
	if test -x ${P}/distro-query
	then
		DISTRO_QUERY="${P}/distro-query"
		break
	fi
done

if test -n "${DISTRO_QUERY}"
then
	#DISTRO="$($DISTRO_QUERY |awk '/compat / { printf("%s-",$3) }')${ARCH}"
	DISTRO="$(perl -I${OSCAR_HOME}/lib $DISTRO_QUERY --compat_distro_id)"
	echo "${URL_BASE}/${OSCAR_VERSION}/${DISTRO}"
	exit 0
else
	echo "ERROR: Unable to find distro-query script in /usr/bin \${OSCAR_HOME}/scripts"
	echo "       Please check your OSCAR installation"
	exit 1
fi
