######################################################################
# Automatically generated by qmake (2.01a) Fri Nov 2 14:11:36 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += .

# Input
FORMS += src/ORM.ui src/AddRepoWidget.ui
SOURCES += src/main.cpp src/ORM_MainGUI.cpp src/ORM_AddRepoGUI.cpp
HEADERS += src/ORM_MainGUI.h src/ORM_AddRepoGUI.h
