#!/usr/bin/perl

#########################################################################
#  File  : Installer.pl                                                 #
#  Author: Terrence G. Fleury (tfleury@ncsa.uiuc.edu)                   #
#  Date  : April 19, 2004                                               #
#  This perl script executes the OSCAR Qt Installer.  It is based on    #
#  a standard perl-Qt template generated by puic.                       #
#########################################################################
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
#  Copyright (c) 2004 The Board of Trustees of the University of Illinois.
#                     All rights reserved.
#########################################################################

package main;

use Qt;
use lib $ENV{OSCAR_HOME}."/src/Installer";
use InstallerMainWindow qw ( InstallerMainWindow );

print "Intializing the Qt runtime...\n";
my $appl = Qt::Application(\@ARGV);
print "Creating the main window...\n";
my $main = InstallerMainWindow; 
$appl->setMainWidget($main);
$main->show;
exit $appl->exec;

