#!/bin/sh
# Copyright (c) 2002 The Trustees of Indiana University.  
#                    All rights reserved.
# 
# This file is part of the OSCAR software package.  For license
# information, see the LICENSE file in the top level directory of the
# OSCAR source distribution.

# $Id: ssh_user_tests,v 1.1 2002/10/28 23:11:30 mchasal Exp $
#
# test_cluster - script to test MPI, PVM, & PBS
# Authors: Jason Brechin
#          Jeremy Enos


node1=$1

if [ `ping -c 1 $node1 2>/dev/null | grep -c avg` -eq 0 ]; then
  $OSCAR_TESTPRINT --label "SSH ping test" -f
  exit 1;
fi
$OSCAR_TESTPRINT --label "SSH ping test" -p

$OSCAR_TESTPRINT --label "SSH server->node" 
if [ "x`ssh $node1 hostname 2> /dev/null`" = "x$node1" ]; then
  $OSCAR_TESTPRINT --label "SSH server->node" -p 
else
  $OSCAR_TESTPRINT --label "SSH server->node" -f 
  exit 1;
fi

$OSCAR_TESTPRINT --label "SSH node->server"  
server=`hostname`
testval=`ssh $node1 ssh $server hostname 2> /dev/null`
if [ "x$testval" = "x$server" ]; then
  $OSCAR_TESTPRINT --label "SSH node->server" -p 
else
  $OSCAR_TESTPRINT --label "SSH node->server" -p 
  exit 1
fi

exit 0

