#!/bin/sh
# 
# This file is part of the OSCAR software package.  For license
# information, see the COPYING file in the top level directory of the
# OSCAR source distribution.

# $Id: ssh_user_tests,v 1.3 2002/10/30 21:05:38 mchasal Exp $
#
# test_cluster - script to test MPI, PVM, & PBS
# Authors: Jason Brechin
#          Jeremy Enos


node1=$1

if ping -c 1 $node1 >/dev/null 2>&1
then
  $OSCAR_TESTPRINT --label "SSH ping test" -p
else
  $OSCAR_TESTPRINT --label "SSH ping test" -f
fi

$OSCAR_TESTPRINT --label "SSH server->node" 
if ssh $node1 hostname > /dev/null 2>&1
then
  $OSCAR_TESTPRINT --label "SSH server->node" -p 
else
  $OSCAR_TESTPRINT --label "SSH server->node" -f 
fi

$OSCAR_TESTPRINT --label "SSH node->server"  
server=`hostname`
if ssh $node1 ssh $server hostname >/dev/null 2>&1
then
  $OSCAR_TESTPRINT --label "SSH node->server" -p 
else
  $OSCAR_TESTPRINT --label "SSH node->server" -f 
fi

exit 0

