#!/usr/bin/perl

#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
 
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#   This script is designed to be run after the image is built.
#   It will do all the fixups required.

use strict;
use lib "$ENV{OSCAR_HOME}/lib",'/usr/lib/systeminstaller';

use Carp;
use File::Copy;
use SIS::Client;
use OSCAR::Package;
use Data::Dumper;
use Getopt::Long;

my %opts = ();
unless (GetOptions(\%opts,"wait") ) {
        croak("Options incorrect.");
}

my @clientlist;
if (@ARGV) {
        @clientlist=@ARGV;
} else {
        my @mlist = clientList;
        foreach my $m (@mlist) {
                push @clientlist,$m->{NAME};
        }
}

my @pkgs = list_pkg();

my $return = 0;

print "Performing root tests...\n";
# First do the root tests
$ENV{OSCAR_TESTPRINT}=$ENV{OSCAR_HOME}. "/testing/testprint";
foreach my $pkg (@pkgs) {
    if(!run_pkg_user_test("$ENV{OSCAR_HOME}/packages/$pkg/testing/test_root","root",0,join(" ",@clientlist))) {
  #  if(!run_pkg_script($pkg,"test_root",0,join(" ",@clientlist))) {
        $return++;
    } 
}

if($return) {
    print("There were issues running some root test scripts.  Please check your logs\n");
}

# Setup the user environment
#

my $test_user="oscartst";
my ($tu,$tp,$tid,$tgid,$tq,$tcom,$tgcos,$test_user_homedir,$ts)=getpwnam $test_user;
unless ($test_user_homedir) {
          if (system("/usr/sbin/useradd -m $test_user")) {
                  croak("Unable to create test user and run user tests, exitting.");
          }
          ($tu,$tp,$tid,$tgid,$tq,$tcom,$tgcos,$test_user_homedir,$ts)=getpwnam $test_user;
}

# Check for a properly mounted /home dir

system("$ENV{OSCAR_TESTPRINT} --label '/home mounts'");
open(TFILE,">$test_user_homedir/oscartestfile");
print TFILE "OSCAR IS COOL\n";
close(TFILE);
sleep 2; #just in case
my $homecount=0;
foreach my $cli (@clientlist){
        system("$ENV{OSCAR_TESTPRINT} --label '/home mounts' --status '$cli'");
        if (system("ssh $cli ls $test_user_homedir/oscartestfile > /dev/null 2>&1")) {
                $homecount++;
        }
}
if ($homecount) {
        system("$ENV{OSCAR_TESTPRINT} --label '/home mounts' -s "$homecount nodes failed" -f ");
} else {
        system("$ENV{OSCAR_TESTPRINT} --label '/home mounts' -p ");
}
unlink("$test_user_homedir/oscartestfile");





# Now the user tests

print "\nPreparing user tests...\n";

$ENV{OSCAR_TESTPRINT}="$test_user_homedir/testprint";
my @ufiles = qw(testprint ssh_user_tests pbs_test test_cluster); 

# Copy the base files
foreach my $file (@ufiles) {
	copy("$ENV{OSCAR_HOME}/testing/$file",$test_user_homedir);
        chmod(0755,"$test_user_homedir/$file");
	chown($tid,$tgid,"$test_user_homedir/$file");
}

# Copy the packages test files to the user home dir.
foreach my $pkg (@pkgs) {
    if (-d "$ENV{OSCAR_HOME}/packages/$pkg/testing") {
	mkdir("$test_user_homedir/$pkg/");
        # I know, shell badness, but so much easier than doing
	# a recursive thing in perl.
	system("cp -af $ENV{OSCAR_HOME}/packages/$pkg/testing/* $test_user_homedir/$pkg/");
	system("chown -R $tid:$tgid $test_user_homedir/$pkg/");
    }
}

# First test ssh
#
# Make sure ssh keys are generated quietly
system("/bin/su -c '' - $test_user > /dev/null 2>&1");

my $clistring=join(" ",@clientlist);

print "Performing user tests...\n";

my $script = "$test_user_homedir/ssh_user_tests";
my $rc = system("su --command='OSCAR_TESTPRINT=$ENV{OSCAR_TESTPRINT} OSCAR_HOME=$ENV{OSCAR_HOME} $script $clistring' - $test_user");

my $creturn=0;

foreach my $pkg (@pkgs) {
    if (-e "$test_user_homedir/$pkg/test_user") {

    	if(!run_pkg_user_test("$test_user_homedir/$pkg/test_user",$test_user,0,join(" ",@clientlist))) {
        	$creturn++;
    	}
    }
}

if($creturn) {
    print("There were issues running some user test scripts.  Please check your logs\n");
}

if ($opts{wait}) {
        waitexit($return);
} else {
        exit($return);
}



sub waitexit {
        my $rc=shift;
        print "...Hit enter to exit...\n";
        my $key=<STDIN>;
        exit $rc;
}        

