#!/bin/bash
#
# Copyright (c) 2003 The Trustees of Indiana University.
#                         All rights reserved.
#
# This file is part of the OSCAR software package.  For license
# information, see the COPYING file in the top level directory of the
# OSCAR source distribution.
#
# $Id: setup,v 1.3 2004/02/06 19:46:50 brechin Exp $
#
# setup script for the update-rpms package
#

# Matt Garrett, <magarret@OSL.IU.edu>
# New version of update-rpms and new directory structure
# David N. Lombard  dnl@speakeasy.net
# New version of update-rpms
# script cleanup

# What does this do?!
VERSION=$(echo "$Revision: 1.3 $" | cut --fields 2 --delimiter " ")

PACKAGE=update-rpms
if [[ $0 = /*/ ]] ; then
  MEDIA_DIR=${0%/*}/../RPMS
else
  MEDIA_DIR=${0%/*/*}/RPMS
fi

RPM_CACHE=/tftpboot/rpm
RPM_DB_DIR=/var/cache/$PACKAGE

CURRENT=$(ls --sort=version --reverse $MEDIA_DIR/$PACKAGE-*.noarch.rpm | head -1)
#CURRENT=${CURRENT%.md5sum} # strip any .md5sum suffix

echo "Installing $CURRENT"
rpm --upgrade $CURRENT

[[ -d $RPM_DB_DIR ]] || mkdir -p $RPM_DB_DIR
if [[ -d $RPM_CACHE ]]; then
  echo "Creating RPM cache database..."
  cd $RPM_DB_DIR
  $PACKAGE --cache=u --url $RPM_CACHE
else
  echo "WARNING: No RPM cache database exists."
  echo "Am I being run from \"install_cluster --> wizard_prep\"?"
fi

echo "Done."
