#!/usr/bin/env perl

# Copyright (c) 2002 The Trustees of Indiana University.  
#                    All rights reserved.
# 
# This file is part of the OSCAR software package.  For license
# information, see the COPYING file in the top level directory of the
# OSCAR source distribution.
#
# $Id: setup,v 1.1 2003/07/04 14:42:39 jsquyres Exp $
#

use strict;
use lib "$ENV{OSCAR_HOME}/lib";
use OSCAR::Logger;
use Carp;

# Version included in media directory

my $ver = "2.14-2.1.el3.rf";
my $real_name = "perl-XML-Simple";
my $module_name = "XML::Simple";

# Helper subroutine

sub do_run {
    my $cmd = join(' ', @_);
    if (system($cmd) != 0) {
	croak("Not able to execute: $cmd");
    }
}

# See if we need to install the perl module

oscar_log_subsection("Checking to see if we need to install $module_name");
my $eval_str = "{ require $module_name }";
eval $eval_str;
if ($@) {
    oscar_log_subsection("$module_name is not yet installed");

    my $topdir = "$ENV{OSCAR_HOME}/share/prereqs/$real_name";
    #my $tarball = "$topdir/media/$real_name-$ver.tar.gz";
    my $tempdir = "/tmp/oscar-install-$real_name.$$";

    mkdir($tempdir) or carp("Can't create temp dir: $tempdir");
    chomp(my $pwd = `pwd`);
    chdir($tempdir);

    my $rpmsdir = "$ENV{OSCAR_HOME}/share/prereqs/$real_name/RPMS";
 
    opendir(RPMS, "/tftpboot/rpm");
    my @rpmsindir = readdir(RPMS);
    closedir(RPMS);
    # check if the rpm is in /tftpboot/rpm
    if ( !(grep( /^$real_name/, @rpmsindir ) ) ) {
       # there's no package there, copying one from sis's
       system ("cp $rpmsdir/$real_name-$ver.noarch.rpm /tftpboot/rpm");
    }
    #check if the package is already installed and if it's not...
    if ( `rpm -qa | grep -c $real_name` == 0 ) {
       system("rpm -Uvh /tftpboot/rpm/$real_name-$ver.noarch.rpm");
    } else {
       print "The package $real_name is already installed";
    }
    
    oscar_log_subsection("$module_name installed successfully");

    chdir($pwd);
    system("rm -rf $tempdir");
} 

# It's already installed -- nothing to do

else {
    oscar_log_subsection("$module_name appears to be installed already");
}

# All done

0;
