#!/usr/bin/env perl

# Copyright (c) 2002 The Trustees of Indiana University.  
#                    All rights reserved.
# 
# This file is part of the OSCAR software package.  For license
# information, see the COPYING file in the top level directory of the
# OSCAR source distribution.
#
# $Id: setup,v 1.3 2003/07/22 22:26:07 brechin Exp $
#

use strict;
use lib "$ENV{OSCAR_HOME}/lib";
use OSCAR::Logger;
use Carp;

# Version included in media directory

my $ver = "2.31";
my $real_name = "XML-Parser";
my $module_name = "XML::Parser";

# Helper subroutine

sub do_run {
    my $cmd = join(' ', @_);
    if (system($cmd) != 0) {
	croak("Not able to execute: $cmd");
    }
}

# See if we need to install the perl module

oscar_log_subsection("Checking to see if we need to install $module_name");
my $eval_str = "{ require $module_name }";
eval $eval_str;
if ($@) {
    oscar_log_subsection("$module_name is not yet installed");
    
    my $topdir = "$ENV{OSCAR_HOME}/share/prereqs/$real_name";
    my $tarball = "$topdir/media/$real_name-$ver.tar.gz";
    my $tempdir = "/tmp/oscar-install-$real_name.$$";

    mkdir($tempdir) or carp("Can't create temp dir: $tempdir");
    chomp(my $pwd = `pwd`);
    chdir($tempdir);

    oscar_log_subsection("Checking expat dependency");
    my $expat = `rpm -qa | grep expat | grep -c devel`;
    chomp $expat;
    if ( $expat == 0 ) {
      oscar_log_subsection("It doesn't look like expat is installed");
      oscar_log_subsection("Installing the expat libraries (expat or libexpat0)...");
      opendir(RPMS, "/tftpboot/rpm");
      my @rpmsindir = readdir(RPMS);
      closedir(RPMS);
      if ( grep( /^libexpat0/, @rpmsindir ) ) {
        #Mandrake - install libexpat0
	if ( `rpm -qa | grep -c libexpat0` != 0 ) {
          system("rpm -Uvh /tftpboot/rpm/libexpat0-devel*.rpm");
	} else {
          system("rpm -Uvh /tftpboot/rpm/libexpat0-*.rpm");
	}
      } else {
        #elsewhere - install expat
	if ( `rpm -qa | grep -c expat` != 0 ) {
          system("rpm -Uvh /tftpboot/rpm/expat-devel*.rpm");
	} else {
	  system("rpm -Uvh /tftpboot/rpm/expat-*.rpm");
        }
      }
    }
    
    # ------------- HERE ARE THE LINES THAT INSTALL perl-devel FOR MANDRAKE ---------------------
    # For Mandrake 10.0
    # The Makefile of XML-Parser and XML-Simple are dependent of libraries provided by perl-devel
    ######## This can be done in a different way, installing perl-XML-Parser rpm from /tftpboot/rpm
    #instead of perl-devel. In one way or another, the packages perl-XML-Parser and perl-devel will
    #be installed by other OSCAR scripts before the end of the installation. The question here is if
    #we want to install XML-Parser from the tarball or from the distribution cds.
#    if ( `rpm -qa | grep -c mandrake-release` != 0 ) {
#      if ( `rpm -qa | grep -c perl-devel` == 0 ) {    
#	  oscar_log_subsection("This is a Mandrake system, installing perl-devel:");
#	  opendir(RPMS, "/tftpboot/rpm");
#          my @rpmsindir = readdir(RPMS);
#          closedir(RPMS);
#          if ( grep( /^perl-devel/, @rpmsindir ) ) {  
#	     system("rpm -Uvh /tftpboot/rpm/perl-devel*.rpm");
#          }
#	  else {
#	   oscar_log_subsection("Couldn't find perl-devel at /tftpboot/rpm - I may not be able to install XML-Parser...");
#          }
#      }
#    }

#    ------------ HERE ARE THE LINES THAT INSTALL THE PACKAGE FROM THE TARBALL ---------------
#    do_run("tar zxf $tarball");
#    croak("Not able to chdir($real_name-$ver)")
#	if (!chdir("$real_name-$ver"));
#    do_run("perl Makefile.PL");
#    do_run("make all");
#    do_run("make install");


#    ------------- HERE WE'LL INSTALL THE PACKAGE FROM THE RPM -----------------------------    
     oscar_log_subsection("Installing perl-XML-Parser"); 
     opendir(RPMS, "/tftpboot/rpm");
     my @rpmsindir = readdir(RPMS);
     closedir(RPMS);
     # check if the rpm is in /tftpboot/rpm
     if ( grep( /^perl-XML-Parser/, @rpmsindir ) ) {
        # chek if it'n not already installed
	if ( `rpm -qa | grep -c perl-XML-Parser` == 0 ) {
          system("rpm -Uvh /tftpboot/rpm/perl-XML-Parser*.rpm");
	} else {
          print "The package perl-XML-Parser is already installed";
	}
     } else {
        croak("perl-XML-Parser is missing from /tftpboot/rpm");
	# we can maintain the tarball and install it here if no rpm was found - this only
	# in case the distro doesn't came with one - RedHat 9, perhaps?
     }	


    oscar_log_subsection("$module_name installed successfully");

    chdir($pwd);
    system("rm -rf $tempdir");
} 

# It's already installed -- nothing to do

else {
    oscar_log_subsection("$module_name appears to be installed already");
}

# All done

0;
