#!/bin/sh
#
# Copyright (c) 2004, The Board of Trustees of the University of Illinois.
#                     All rights reserved.
# Copyright (c) 2004 The Trustees of Indiana University.
#                         All rights reserved.
#
# This file is part of the OSCAR software package.  For license
# information, see the COPYING file in the top level directory of the
# OSCAR source distribution.
#
# $Id: setup,v 1.4 2004/05/13 13:06:08 jsquyres Exp $
#
# setup script for the packman-depman package
#

# Install the relevant RPMs.  Easy enough to hard-code for now, since
# we only handle Linux/RPM.  This script will likely get more complicated.

rpms="packman-depman packman-depman-rpms"

echo "Checking for packman/depman RPMs..."
need_to_install=
for rpm in $rpms; do
	rpm -q $rpm >/dev/null 2>&1
	if test $? = 1; then
		rpm_filename="`ls -1 $OSCAR_HOME/share/prereqs/packman/RPMS/$rpm-[0-9]*rpm`"
		need_to_install="$rpm_filename $need_to_install"
		echo "--> will install $rpm"
	fi
done

if test -n "$need_to_install"; then
	echo "Installing: $need_to_install"
	rpm -Uvh $need_to_install
fi

# All done

exit 0
