#!/bin/bash
#
# Copyright (c) 2004, The Board of Trustees of the University of Illinois.
#                     All rights reserved.
# Copyright (c) 2004 The Trustees of Indiana University.
#                         All rights reserved.
#
# This file is part of the OSCAR software package.  For license
# information, see the COPYING file in the top level directory of the
# OSCAR source distribution.
#
# $Id: setup,v 1.3 2004/05/08 17:42:28 jsquyres Exp $
#
# setup script for the packman-depman package
#

VERSION=$(echo "$Revision: 1.3 $" | cut --fields 2 --delimiter " ")

PACKAGE=packman-depman
if [[ $0 = */* ]] ; then
  MEDIA_DIR=${0%/*}/../RPMS
else
  MEDIA_DIR=${0%/*/*}/RPMS
fi

CURRENT=$(ls -1 --sort=version --reverse "${MEDIA_DIR}/${PACKAGE}"-*.noarch.rpm | head -1)
rpm -q packman-depman >/dev/null 2>&1
if [ "x$?" == "x1" ]; then
  echo "Installing ${CURRENT##*/} in $OSCAR_HOME"
  echo rpm -Uvh "${CURRENT}"
  rpm -Uvh "${CURRENT}"
  echo "Done."
else
  echo "No need to install packman-depman"
fi
