#!/bin/csh
#
# $Id: build-package-docs,v 1.5 2002/09/11 01:26:33 jsquyres Exp $
#
# $COPYRIGHT$
#

# Look in ../packages/* for doc/user.tex files.  When we find those
# files, add them to package-docs.tex.

\cp -f package-docs.tex.in package-docs.tex

# Don't use a glob here, because this directly affects the ordering of
# sections in the output doc.  So pipe the output of ls here though
# sort so that we can have deterministic ordering of the sections.

foreach file (`ls ../../packages/*/doc/user.tex | sort`)
    set dir="`dirname $file`"
    set dir="`dirname $dir`"
    if (! -f $dir/.oscar_ignore) then
	echo "\input{$file}" >> package-docs.tex
    endif
end
