#!/bin/csh
#
# $Id: build-package-license,v 1.1 2002/06/19 17:33:50 mchasal Exp $
#
# $COPYRIGHT$
#

# Look in ../packages/* for doc/user.tex files.  When we find those
# files, add them to package-docs.tex.

cp -f package-license.tex.in package-license.tex

# Don't use a glob here, because this directly affects the ordering of
# sections in the output doc.  So pipe the output of ls here though
# sort so that we can have deterministic ordering of the sections.

foreach file (`ls ../../packages/*/doc/license.tex | sort`)
    echo "\input{$file}" >> package-license.tex
end
