#!/bin/csh
#
# $Id: build-package-docs,v 1.4 2002/06/20 05:56:07 jsquyres Exp $
#
# $COPYRIGHT$
#

# Look in ../packages/* for doc/user.tex files.  When we find those
# files, add them to package-docs.tex.

\cp -f package-docs.tex.in package-docs.tex

# Don't use a glob here, because this directly affects the ordering of
# sections in the output doc.  So pipe the output of ls here though
# sort so that we can have deterministic ordering of the sections.

foreach file (`ls ../../packages/*/doc/user.tex | sort`)
    echo "\input{$file}" >> package-docs.tex
end
