#!/usr/bin/env perl

# Copyright (c) 2002 The Trustees of Indiana University.  
#                    All rights reserved.
# 
# This file is part of the OSCAR software package.  For license
# information, see the COPYING file in the top level directory of the
# OSCAR source distribution.
#
# $Id: install,v 1.1 2002/10/31 22:02:21 ngorsuch Exp $
#

#use strict;
use lib "$ENV{OSCAR_HOME}/lib";
use OSCAR::Logger;
use Carp;

# Version included in media directory

my $ver = "0.90";
my $package_dir = "oda";

# Helper subroutine

sub do_run {
    my $cmd = join(' ', @_);
    if (system($cmd) != 0) {
	croak("Not able to execute: $cmd");
    }
}

# list of rpm names to check for and rpm files to install
my @rpms = qw( mysql
	       mysql-server
	       perl-DBD-MySQL
	       perl-DBI
	       oda );

# find out where the corresponding rpm files are
my @rpm_files = ();

# read in the file names in this package's RPMS directory
my $package_rpms_dir = "$ENV{OSCAR_HOME}/packages/$package_dir/RPMS";
opendir(DIR, "$package_rpms_dir" )
    || die "$0: CANNOT OPEN RPMS DIRECTORY $package_rpms_dir TO FIND RPMS FOR ODA";
my @package_rpm_files = readdir(DIR);
chomp @package_rpm_files;
closedir DIR;

# read in the file names in the oscar base rpms directory
my $oscar_rpms_dir = "/tftpboot/rpm";
opendir(DIR, "$oscar_rpms_dir" )
    || die "$0: CANNOT OPEN RPMS DIRECTORY $oscar_rpms_dir TO FIND RPMS FOR ODA";
my @oscar_rpm_files = readdir(DIR);
chomp @oscar_rpm_files;
closedir DIR;

my $error_flag = 0;
foreach my $rpm ( @rpms ) {
    oscar_log_subsection("Checking if rpm <$rpm> is already installed");
    my $command = "rpm -q $rpm 2>/dev/null";
    if ( system($command) == 0 ) {
	oscar_log_subsection("rpm <$rpm> is already installed");
	next;
    }
    oscar_log_subsection("Looking for the rpm file to install <$rpm>");
    my @package_matching_rpm_files = 
	grep ( /^$rpm\-[0-9][0-9\.]*\-/, @package_rpm_files );
    my @oscar_matching_rpm_files =
	grep ( /^$rpm\-[0-9][0-9\.]*\-/, @oscar_rpm_files );
    if ( scalar @oscar_matching_rpm_files > 1 ) {
	warn "rpm <$rpm> for ODA matched too many files <@oscar_matching_rpm_files> in <$oscar_rpms_dir>\n";
	oscar_log_subsection("rpm <$rpm> for ODA matched too many files <@oscar_matching_rpm_files> in <$oscar_rpms_dir>\n");
	$error_flag = 1;
    } elsif ( scalar @oscar_matching_rpm_files == 1 ) {
        my $rpm_file = "$oscar_rpms_dir/$oscar_matching_rpm_files[0]";
	print "rpm <$rpm> will be supplied by file <$rpm_file>";
	oscar_log_subsection("<$rpm> will be supplied by the rpm file <$rpm_file>");
	push @rpm_files, $rpm_file;
    } elsif ( scalar @package_matching_rpm_files > 1 ) {
	warn "rpm <$rpm> for ODA matched too many files <@package_matching_rpm_files> in <$package_rpms_dir>\n";
	oscar_log_subsection("rpm <$rpm> for ODA matched too many files <@package_matching_rpm_files> in <$package_rpms_dir>\n");
	$error_flag = 1;
    } elsif ( scalar @package_matching_rpm_files == 1 ) {
        my $rpm_file = "$package_rpms_dir/$package_matching_rpm_files[0]";
	print "rpm <$rpm> will be supplied by file <$rpm_file>";
	oscar_log_subsection("<$rpm> will be supplied by the rpm file <$rpm_file>");
	push @rpm_files, $rpm_file;
    } else {
	warn "rpm <$rpm> for ODA does not have a matching file in $oscar_rpms_dir or $package_rpms_dir";
	oscar_log_subsection("rpm <$rpm> for ODA does not have a file in $oscar_rpms_dir or $package_rpms_dir");
	$error_flag = 1;
    }
}
if ( $error_flag ) {
    oscar_log_subsection("ODA is giving up and will not be installed !!!!!");
    die "ODA WILL NOT BE INSTALLED BECAUSE OF THE ABOVE ERRORS!!!!!";
}
if ( @rpm_files ) {
    oscar_log_subsection("ODA is installing these rpm files:");
    foreach my $rpm_file ( @rpm_files ) {
	oscar_log_subsection("     $rpm_file");
    }
    my $command = "rpm -ivh " . join( ' ', @rpm_files );
    do_run( $command );
}

# All done

0;
