#!/usr/bin/env perl

# Copyright (c) 2002 The Trustees of Indiana University.  
#                    All rights reserved.
# 
# This file is part of the OSCAR software package.  For license
# information, see the COPYING file in the top level directory of the
# OSCAR source distribution.
#
# $Id: install,v 1.4 2002/11/16 03:19:52 bligneri Exp $
#

#use strict;
use lib "$ENV{OSCAR_HOME}/lib";
use OSCAR::Logger;
use Carp;
use OSCAR::Distro;
use OSCAR::Package;
use XML::Simple;

# Version included in media directory

my $ver = "0.90";
my $package_dir = "oda";


# Definition of distro type and version
my ($distro_name, $distro_version) = which_distro_server();
# Helper subroutine

sub do_run {
    my $cmd = join(' ', @_);
    if (system($cmd) != 0) {
	croak("Not able to execute: $cmd");
    }
}

# find a list of rpm names to check for and rpm files to install
my @rpms = ( );
# start by seeing if we're on a redhat system,
# don't bother with redhat versions since the
# following rpm set works on all the versions
# oscar works on


if ( $distro_name eq "RedHat") {
    @wanted_rpms = qw( mysql
		perl-DBD-MySQL
		perl-DBI
		mysql-server
		oda );

}
elsif ($distro_name eq "Mandrake") { 
    @wanted_rpms = qw( MySQL
        MySQL-client
		perl-DBI
		perl-Mysql
		perl-ExtUtils-PerlPP
		oda );
        # FIXME (bligneri)
        # Will just copy the XML file.
        # Should be an argument in the XML file.
        #my $xs = new XML::Simple(forcearray => 1, keeproot => 1);
        #my $config = $xs->XMLin($ENV{"OSCAR_HOME"}."/packages/oda/config.xml");
        my $command="cp -f ".$ENV{"OSCAR_HOME"}."/packages/oda/config.xml.mandrake ".$ENV{"OSCAR_HOME"}."/packages/oda/config.xml";
        system $command;
}

# find out where the corresponding rpm files are
my @rpm_files = ();

# read in the file names in this package's RPMS directory
my $package_rpms_dir = "$ENV{OSCAR_HOME}/packages/$package_dir/RPMS";
opendir(DIR, "$package_rpms_dir" )
    || die "$0: CANNOT OPEN RPMS DIRECTORY $package_rpms_dir TO FIND RPMS FOR ODA";
my @package_rpm_files = readdir(DIR);
chomp @package_rpm_files;
closedir DIR;

# read in the file names in the oscar base rpms directory
my $oscar_rpms_dir = "/tftpboot/rpm";
opendir(DIR, "$oscar_rpms_dir" )
    || die "$0: CANNOT OPEN RPMS DIRECTORY $oscar_rpms_dir TO FIND RPMS FOR ODA";
my @oscar_rpm_files = readdir(DIR);
chomp @oscar_rpm_files;
closedir DIR;

my $error_flag = 0;

install_rpms(@wanted_rpms) or croak("ODA is giving up and will not be installed !!!!!");

if ( @rpm_files ) {
    oscar_log_subsection("ODA is installing these rpm files:");
    foreach my $rpm_file ( @rpm_files ) {
	oscar_log_subsection("     $rpm_file");
    }
    my $command = "rpm -ivh " . join( ' ', @rpm_files );
    do_run( $command );
}

# All done

0;
