#!/usr/bin/env perl

# Copyright © 2003, The Board of Trustees of the University of Illinois. All rights reserved.
# Copyright (c) 2002 The Trustees of Indiana University.  
#                    All rights reserved.
# Copyright (c) 2005, Revolution Linux
# Copyright (c) 2006, Erich Focht
#                     All rights reserved
# 
# This file is part of the OSCAR software package.  For license
# information, see the COPYING file in the top level directory of the
# OSCAR source distribution.
#
# $Id$
#

use strict;
use lib "$ENV{OSCAR_HOME}/lib";
use OSCAR::Logger;
use OSCAR::PackagePath;

my $os = OSCAR::PackagePath::distro_detect_or_die();
my $mysqld;

if ($os->{compat_distro} =~ /^(rhel|fc|mdv)/) {
    $mysqld      = 'mysqld';
} elsif ($os->{compat_distro} =~ /^(suse|mdk)/) {
    $mysqld      = 'mysql';
} else {
    print "\n\nCannot determine distribution and version!!!!\nCannot determine oda rpms to install!!!!\n\n";
    exit 1;
}

oscar_log_subsection("Checking status of MySQL server $mysqld");
if (! -x "/etc/init.d/$mysqld") {
    croak("Couldn't find /etc/init.d/$mysqld. MySQL server not correctly installed?");
}
if ( !system("/etc/init.d/$mysqld status | grep -c stopped") ) {
  !system("/etc/init.d/$mysqld restart") or croak("Couldn't restart $mysqld");
} else {
  oscar_log_subsection("$mysqld already running");
}

exit(0);
