#!/usr/bin/perl
#
# Copyright (c)           Erich Focht <efocht@hpce.nec.com>
#                         All rights reserved.
# Copyright (c) 2007-2008 Oak Ridge National Laboratory
#                         Geoffroy Vallee <valleegr@ornl.gov>
#                         All rights reserved
#
# This file is part of the OSCAR software package.  For license
# information, see the COPYING file in the top level directory of the
# OSCAR source distribution.
#
# $Id$
#

use strict;
use lib "$ENV{OSCAR_HOME}/lib";
use File::Basename;
use OSCAR::OCA::OS_Detect;

$ENV{LC_ALL}="C";

my @odir = @ARGV;

help_and_die() if (!scalar(@odir));

my $os = OSCAR::OCA::OS_Detect::open();
my $dist = $os->{compat_distro};
my $ver  = $os->{compat_distrover};
my $arch = $os->{arch};

for my $d (@odir) {
    $d =~ s,/$,,g;
    &opkgc_rpms($d);
}
exit 0;



sub opkgc_rpms {
    my ($dir) = @_;

    my $tdir = $dir."/distro/".$dist.$ver."-".$arch;
    chomp(my $tmpo = `mktemp /tmp/bld_opkg_XXXXXXX`);

    my $cmd = "opkgc -v -v -v --dist $dist --input $dir > $tmpo 2>&1";
    print "Executing: $cmd...\n";
    my $err = system($cmd);
    #system("cat $tmpo");
    if ($err) {
	print "EEEE: Building opkg RPMs for $dir failed.\n";
        my $efile = "$dir.err";
	!system("mv $tmpo $efile")
	    or die "Could not move $tmpo to $efile: $!";
	print "=EE= Full output is in $efile =EE=\n";
	exit 1;
    } else {
	local *IN;
	open IN, "$tmpo" or die "Could not open file $tmpo";
	while (<IN>) {
	    chomp;
	    if (/^\[DEBUG\] Wrote: (.*)$/) {
		my $file = $1;
		if ($file =~ /.noarch.rpm$/) {
		    if (! -d $tdir) {
			!system("mkdir -p $tdir")
			    or die "Could not create $tdir: $!";
		    }
		    !system("mv $file $tdir")
			or die "Could not move $file to $tdir";
		    print "Created ".$tdir."/".basename($file)."\n";
		}
	    }
	}
	close IN;
	!system("rm $tmpo") or die "Could not remove $tmpo : $!";
    }
}

sub help_and_die () {
    print "Usage: $0 <OPKG_PATH> ...\n";
    exit 1;
}

__END__

=head1 NAME

build_opkg_rpms, a command line tool that builds RPMs for a given OSCAR package,
based on available SRPM(s) for that specific OSCAR package. It is possible to
create RPMs for multiple OSCAR package at the same time.

=head1 SYNOPSIS

build_opkg_rpms OPTIONS

=head1 SYNTAX

build_opkg_rpms <opkgs_dirs>, where <opkgs_dirs> is a list of directory of OSCAR
packages for which RPMs need to be created.

=head1 SEE ALSO

perl(1)

=cut
