#!/bin/sh

# Copyright (c) 2003, The Board of Trustees of the University of Illinois.
#                     All rights reserved.
# Author: Jason Brechin
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
# client_status - Takes client hostnames as arguments
#		  and reports their install status
# $Id$

for node in $*; do

building=`netstat -tu | grep "$node" | grep -c rsync`
pingable=`ping -w 4 -nc 2 $node >/dev/null 2>&1; echo $?`
pbsfree=`pbsnodes -a | grep -A1 $node | tail -1 | grep -c free`
case "$pingable" in
  2)
    echo "Unknown host: $node"
    ;;
  1)
    echo "$node is NOT pingable"
    ;;
  0)
    echo "$node is pingable"
    if [ $building -gt 0 ]; then
      echo "$node is building"
    else
      echo "$node is NOT building"
    fi
    if [ $pbsfree -gt 0 ]; then
      echo "$node is marked as free (according to PBS)"
    else
      echo "$node is NOT marked as free (according to PBS)"
    fi
    ;;
  *)
  echo "I don't know what happened when trying to ping $node"
esac

done
