#!/usr/bin/env perl
#
# Copyright (c) 2002-2005 The Trustees of Indiana University.  
#                         All rights reserved.
# Copyright (c) 2005 Bernard Li <bli@bcgsc.ca>
# 
# This file is part of the OSCAR software package.  For license
# information, see the COPYING file in the top level directory of the
# OSCAR source distribution.
#
#
# $Id$
#
# (c) 2005 Erich Focht <efocht@hpce.nec.com>

use strict;
use lib "$ENV{OSCAR_HOME}/lib";
use POSIX;
use Carp;
use OSCAR::OCA::OS_Detect;
use OSCAR::PackagePath;
use Getopt::Long;
use Data::Dumper;

sub vprint;

# One must always protect oneself.
#
die "\$OSCAR_HOME: not defined.\n" unless exists $ENV{OSCAR_HOME};
die "$ENV{OSCAR_HOME}: not a directory.\n" unless -d $ENV{OSCAR_HOME};
die "$ENV{OSCAR_HOME}: not accessible.\n" unless -x $ENV{OSCAR_HOME};

# Different distros require different RPMs. Different architectures, too.

# configure command line options parsing
Getopt::Long::Configure("ignore_case"); # ignore case
Getopt::Long::Configure("auto_abbrev"); # allow abbreviated input

my %options;
GetOptions( \%options,
	    'image|i=s',
	    'pool|p=s',
	    'help|h',
            ) || usage();

usage() if ($options{help});

################################
## Do the job
################################

my $os;
if ($options{pool}) {
    print "Detecting distro pool $options{pool}:\n";
    $os = OSCAR::OCA::OS_Detect::open(pool => $options{pool});
    die "Unable to determine operating system" if (!$os);
    print "Detected os structure :\n".Dumper($os);
} else {
    $os = OSCAR::OCA::OS_Detect::open($options{image});
    die "Unable to determine operating system" if (!$os);
    print "Distro package url : ".&distro_repo_url($options{image})."\n";
    print "OSCAR package pool : ".&oscar_repo_path($options{image})."\n";
    print "Detected os structure :\n".Dumper($os);
}
exit 0;

############################################################################
######## only subroutines below
############################################################################

sub vprint {
    print @_ if ($options{verbose});
}

    print <<END_USAGE;
Usage: distro-query [options]

 Print OS_Detect information.

 Options:
   --image|-i IMAGE_PATH : detect distro and architecture of an image directory
   --pool|-p path        : detect distro and architecture of a package pool
   --help|-h             : display this help text
END_USAGE
   exit(1);
}

