#!/usr/bin/perl

# Copyright (c) 2003, The Board of Trustees of the University of Illinois.
#                     All rights reserved.

#   $Id: mac_collector,v 1.1 2004/02/12 20:01:24 brechin Exp $

#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
 
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use strict;
use Carp;
use lib "$ENV{OSCAR_HOME}/lib";
use OSCAR::MAC;
use OSCAR::Logger;
use OSCAR::Database;


#TESTING    my $cluster_interface = OSCAR::Database::database_read_table_fields('oscar', qw( interface ), undef, undef, 0);

my $cluster_interface='eth1';
my $cmd = "/usr/sbin/tcpdump -i $cluster_interface -nn -e -t -l -p -q broadcast and src port 68 and dst port 67";

my $tcpdumppid = open(TCPDUMP, "$cmd 2>/dev/null |") || carp("Could not run $cmd: $!");

#print "tcpdump pid = $tcpdumppid\n";

my $mac;
my $collect = 1;
while( <TCPDUMP> ) {
  #print "collected: $_\n";
  m/^([\w\d:]{6,17})\W/;
  #print "found: '$1'\n";
  print verify_mac($1) . "\n";
}
close TCPDUMP;

