#!/usr/bin/perl

# Copyright (c) 2003, The Board of Trustees of the University of Illinois.
#                     All rights reserved.

#   $Id$

#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
 
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# $Id$

use strict;
use Carp;
use lib "$ENV{OSCAR_HOME}/lib";
use OSCAR::GUI_MAC;
use OSCAR::Logger;
use OSCAR::Database;
use sigtrap qw(handler sighandle normal-signals);

$| = 1;

my @results;
my @tables = ("oscar");
OSCAR::Database::single_dec_locked("read_records oscar.interface","READ",\@tables,\@results, 0);
my $cluster_interface = $results[0];

my $cmd = "/usr/sbin/tcpdump -i $cluster_interface -nn -e -t -l -p -q broadcast and src port 68 and dst port 67";

my $tcpdumppid = open(TCPDUMP, "$cmd 2>/dev/null |") || carp("Could not run $cmd: $!");

my @pids = split(' ', `ps -C tcpdump -o pid= -o ppid= | grep "$tcpdumppid"` );
$tcpdumppid = $pids[0];

while( <TCPDUMP> ) {
  #print "collected: $_\n";
  m/^([\w\d:]{6,17})\W/;
  #print "found: '$1'\n";
  print verify_mac($1) . "\n";
}
close TCPDUMP;

sub sighandle {
  open(STDERR, ">/dev/null");
  kill 1, $tcpdumppid;
  close TCPDUMP;
  croak;
}
