#!/usr/bin/env perl
#
# Copyright (c) 2007, Oak Ridge National Laboratory.
#                     Geoffroy R. Vallee <valleegr@ornl.gov>
#                     All rights reserved.
# Copyright (c) 2003, The Board of Trustees of the University of Illinois.
#                     All rights reserved.
# Copyright (c) 2002-2003 The Trustees of Indiana University.
#                     All rights reserved.
#
# This file is part of the OSCAR software package.  For license
# information, see the COPYING file in the top level directory of the
# OSCAR source distribution.
#
# $Id: opd2 5017 2006-06-16 15:00:26Z valleegr $
#

use strict;
use Carp;
use lib "$ENV{OSCAR_HOME}/lib";
use Term::ReadLine;
use Getopt::Long;
use OSCAR::opd2 qw(
                    add_repo_to_cache
                    flush_cache
                    get_available_opkgs
                    get_available_repositories
                    get_included_opkgs
                    get_default_repositories
                    init_cache
                    init_opd
                    list_available_opkgs
                    list_available_repositories
                    list_included_opkgs
                  );
use OSCAR::Utils qw (print_array);

my $repository_listing;
my $repository_selected = -1;
our $selected_repo = "";
my $package_listing;
my $verbose = $ENV{OPD_VERBOSE};

my ($interactive, @repos, $default_repo, $list_default_repos);

Getopt::Long::Configure("pass_through");
GetOptions(
        "non-interactive"   => \$interactive, 
        "default-repos" => \$default_repo,
        "list-default-repos" => \$list_default_repos,
        "repo=s"        => \@repos,
        "help"          => \&help,
        );

my $opd_term = new Term::ReadLine 'OPD';

#
# Loop over the main menu
#
sub main_menu {
    my $selection;

#    my $name = $repository_listing->{site}[$repository_selected]->{name};
#    my $uri = $repository_listing->{site}[$repository_selected]->{uri}[0];

#    my $num_pkgs = $#{$package_listing->{package}} + 1;
    my $name = "";
    my $uri = "";
    my $num_pkgs = "";
    my $packages = ($num_pkgs == 1) ?
    "1 package available" :
    "$num_pkgs packages available";

    my $show_info = 1;
    my $cmd;
    my @options;

    # Setup tab completion

    my $attribs = $opd_term->Attribs;
    $attribs->{completion_entry_function} =
    $attribs->{list_completion_function};
    $attribs->{completion_word} =
    [qw(download help info list print quit exit repository update)];

    # Main prompt loop

    while (1) {

#    if ($show_info) {
#        print("
#==> $name
#==> $uri
#==> $packages\n\n");
#        $show_info = 0;
#    }

    # Use GNU Readline to prompt and get input.  Readline rocks.

    last if (!defined($_ = $opd_term->readline("opd> ")));
    next if (!$_);

    # Analyze what we got back

    @options = split(/[ \t]/);
    $cmd = "";
    while (!$cmd && $#options >= 0) {
        $cmd = lc($options[0]);
        shift(@options);
    }
    next if (!$cmd);

    # Change repository

    if (/^a/i || /^add/i) {
        my $url = $opd_term->readline("Enter repository URL>");
        if (!$url) {
            print ("ERROR: no repository has been specified\n");
        next;
        }
#        scan_repository ($url);
    }

    elsif (/^f/i || /^flush/i) {
        flush_cache ();
    }

    # List available OSCAR repositories

    elsif (/^r/i || /^repo/i || /^repos/i || /^repository/i) {
        print("\n");
        print "Available repository:\n";
        list_available_repositories ();
        print("\n");
    }

    # List the packages that are available

    elsif (/^l/i || /^li/i || /^list/i || /^ls/i ) {
        print("\n");
        list_available_opkgs($selected_repo);
        print("\n");
#         print "OPKGs available from the official OSCAR repository:\n";
#         list_included_opkgs ("debian");
#         print("\n");
    }

    # Select a repository

    elsif (/^s/i || /^select/i ) {
        print ("\n");
        print "Select one the following OSCAR repositories:\n";
        my @repos = get_available_repositories ();
        print "\t0: all\n";
        my $i = 1;
        foreach my $repo (@repos) {
            print "\t$i: $repo\n";
        }
        my $valid_selection = 0;
        while ($valid_selection == 0) {
            my $selection = $opd_term->readline("Your selection> ");
            if (defined @repos[$selection-1]) {
                $valid_selection = 1;
                $selected_repo = @repos[$selection-1];
            } else {
                print "ERROR: Invalid selection.\n";
            }
        }
    }

    # Print the help message

    elsif (/^\?/ || /^h/i || /^help/i) {
        print("
[h] help       - This message
[a] add        - Add an OSCAR repository
[s] select     - Select a repository
[i] info       - Display information about the selected repository
[r] repository - Display the list of available OSCAR repositories
[l] list       - Display the list of available OSCAR packages
[f] flush      - Flush the OPD cache
[q] quit       - Quit
R              - Select the specified package(s)

N has an integer value

R can be a single integer value, a range or an enumeration of all that :

  1,2,5-6         - select packages 1,2,5,6\n\n");
    }

    # Show repository info

    elsif (/^i/i || /^in/i || /^info/i) {
        print "\n";
        list_available_repositories ();
        print "\n";
    }

    # Exit

    elsif (/^q/i || /^quit/i ||
         /^e/i || /^exit/i) {
        last;
    }

    # Have no idea -- issue a warning

    else {
        print("\nIllegal command -- ignored\n\n");
    }
    }
}

# First of all, enforce that the user running this script is 'root'
# This is necessary for access to /var/cache/oscar/downloads
croak "You must be 'root' to run this script.  Aborting" if ($< != 0);

if ($interactive) {
    $verbose = 0;
}

init_opd();

if ($interactive || $list_default_repos) {
    if ($list_default_repos) {
        my @list = get_default_repositories ();
        # Then we print the result. Remember that the output is used by
        # other application, only print the strict necessary
        foreach my $item (@list){
            print "$item ";
        }
        print "\n";
        exit (0);
    }
    if ($default_repo) {
        @repos = get_default_repositories ();
    }
    if (!defined @repos) {
        print "Error: you must specify a repository\n";
        exit -1;
    } else {
        my @list = ();
        foreach my $repo (@repos) {
            add_repo_to_cache ($repo);
            my @opkgs = get_available_opkgs($repo);
            foreach my $opkg (@opkgs) {
                push (@list, $opkg);
            }
        }
        # Then we print the result. Remember that the output is used by
        # other application, only print the strict necessary
        foreach my $item (@list){
            print "$item ";
        }
        print "\n";
    }
} else {
    main_menu();
}

sub help {
    print "Usage: $0 OPTIONS\n";
    print "\n";
    print "Call the OPD2 command line, both a interactive and a non-interactive".
          " are available.\n";
    print "OPTIONS can be:\n";
    print " --non-interactive : use OPD2 in non-interactive mode;\n";
    print "                     this option enables options --repo and\n";
    print "                     --default-repos\n";
    print "                     In non-interactive mode, each command gives\n";
    print "                     the list of available OSCAR packages.\n";
    print " --repo URL        : repository which should be used for queries \n";
    print "                     (multiple --repo options are possible).\n";
    print " --help            : this help information.\n";
    print " --default-repos   : gives the list of OPKGs available via the\n";
    print "                     default OSCAR repositories. If this option\n";
    print "                     is used, the option --repo is deactivated.\n";
    print " --list-default-repos : gives the list of default OSCAR repos\n";
    print "\n";
    exit;
}

1;
