#!/usr/bin/env perl
#
# Quick hack to install API opkgs reachable in the configured repositories
# during wizzard preparation.
#
# Copyright 2007 Erich Focht <efocht@hpce.nec.com>
#                All rights reserved.
# 
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# $Id$

my $verbose = 1;

# get packages list and version
my %opkgs;

my $verbose_switch="";
my $verbose_switch="--verbose" if $verbose;

my $cmd="/usr/bin/yume $verbose --repoquery --nevra opkg-*-server";
print "Running $cmd" if $verbose;
open CMD, "$cmd |" or die "Error: $!";
while (<CMD>) {
    if (m/^opkg-(.*)-server-(.*).noarch.rpm/) {
	$opkgs{$1} = $2;
    }
}
close CMD;

print "Found following packages in the repository:\n";
for my $p (sort keys(%opkgs)) {
    printf("%-40s - %s\n", $p, $opkgs{$p});
}

print "Installing the opkg API metapackages...\n";

my $cmd = "/usr/bin/yume $verbose -y install";
for my $p (sort keys(%opkgs)) {
    $cmd .= " $p-$opkgs{$p}";
}

print "Executing command: $cmd\n" if $verbose;
my $err = system($cmd);
print "Error: $cmd failed: $!\n" if $err;
exit $err;
