#!/usr/bin/perl -w
# $Id$
#
# Copyright (c) 2007 Oak Ridge National Laboratory.
#                    Geoffroy Vallee <valleegr@ornl.gov>
#                    All rights reserved.
#

BEGIN {
    if (defined $ENV{OSCAR_HOME}) {
        unshift @INC, "$ENV{OSCAR_HOME}/lib";
    }
}

use Data::Dumper;
use OSCAR::OCA::Sanity_Check;
use Carp;

print "Sanity check of the system...\n";

my $sanity = OSCAR::OCA::Sanity_Check::open();

if( not defined($sanity) ) {
    carp ("Error: Sanity_Check open failed.");
} # else {
#    print( " Dump...\n" . Dumper($sanity) );
#}

=head1 NAME

oscar_sanity_check, a command line tool to check OSCAR sanity.

=head1 SYNOPSIS

oscar_sanity_check

=head1 DESCRIPTION

oscar_sanity_check is a command line tool to check OSCAR sanity. This tools is
based on the Sanity_Check OSCAR framework (which is based on the OSCAR 
Component Architecture - OCA). For more information, please refer to the OSCAR
documentation.

=head1 Options

None.

=head1 AUTHOR

Geoffroy Vallee, valleegr@ornl.gov

=head1 SEE ALSO

perl(1)

=cut
