#!/usr/bin/env perl
#

#
# Copyright (c) 2007 Oak Ridge National Laboratory.
#                    Geoffroy R. Vallee <valleegr@ornl.gov>
#                    All rights reserved.
#
# This file is part of the OSCAR software package.  For license
# information, see the COPYING file in the top level directory of the
# OSCAR source distribution.
#

#
# $Id: oscar-config 5017 2006-06-16 15:00:26Z valleegr $
#

use strict;
use Cwd qw(chdir cwd);
use Getopt::Long;

my ($distro_to_setup,
    $distro_repo_to_use,
    $distro_repo,
    $oscar_repo,
    $oscar_repo_to_use,
    $distro_repo_to_mirror,
    $oscar_repo_to_mirror,
    $network
    $bootstrap);

GetOptions(
        "list-setup-distros"            => \&display_list_setup_distros,
        "supported-distros"             => \&display_list_supported_distros,
        "setup-distro=s"                => \$distro_to_setup,
        "display-default-distro-repo=s" => \$distro_repo,
        "display-default-oscar-repo=s"  => \$oscar_repo,
        "use-distro-repo=s"             => \$distro_repo_to_use,
        "use-oscar-repo=s"              => \$oscar_repo_to_use,
        "mirror-distro-repo=s"          => \$distro_repo_to_mirror,
        "mirror-oscar-repo=s"           => \$oscar_repo_to_mirror,
#         "network"                       => \$network,
        "bootstrap"                     => \&bootstrap,
        "help"                          => \&help,
        ) || help();


if (!defined $ENV{OSCAR_HOME}) {
    die ("ERROR: OSCAR_HOME not found");
} else {
    use lib "$ENV{OSCAR_HOME}/lib";
}

if ($distro_repo_to_mirror) {
    if (!defined $distro_to_setup || $distro_to_setup eq "") {
        die "If you want to mirror a repository, you have to tell us for which".
            " distro the repository is made for (for that use the ".
            "--setup-distro option\n";
    }
    require OSCAR::PackagePath;
    require OSCAR::Distro;
    OSCAR::PackagePath::mirror_repo ($distro_repo_to_mirror,
                                     $distro_to_setup,
                                     "/tftpboot/distro");
    OSCAR::PackagePath::use_distro_repo ($distro_to_setup,
                                    "file:///tftpboot/distro/$distro_to_setup");
}

if ($oscar_repo_to_mirror) {
    if (!defined $distro_to_setup || $distro_to_setup eq "") {
        die "If you want to mirror a repository, you have to tell us for which".
            " distro the repository is made for (for that use the ".
            "--setup-distro option\n";
    }
    require OSCAR::PackagePath;
    require OSCAR::Distro;
    OSCAR::PackagePath::mirror_repo ($oscar_repo_to_mirror,
                                     $distro_to_setup,
                                     "/tftpboot/oscar");
    OSCAR::PackagePath::use_distro_repo ($distro_to_setup,
                     "file:///tftpboot/oscar/$distro_to_setup");
}

if ($distro_repo) {
    require OSCAR::PackagePath;
    require OSCAR::Distro;
    # We display the distro repo that is used with the distro
    my $url = OSCAR::PackagePath::get_default_distro_repo ($distro_repo);
    print "$url\n";
}

if ($oscar_repo) {
    require OSCAR::Distro;
    require OSCAR::PackagePath;
    # We display the OSCAR repo that is used with the distro
    my $url = OSCAR::PackagePath::get_default_oscar_repo ($oscar_repo);
    print "$url\n";
}

if ($distro_to_setup) {
    require OSCAR::PackagePath;
    require OSCAR::Distro;
    if ($oscar_repo_to_use eq "") {
        OSCAR::PackagePath::use_default_oscar_repo ($distro_to_setup);
    } else {
        OSCAR::PackagePath::use_oscar_repo ($distro_to_setup,
                                            $oscar_repo_to_use);
    }

    if ($distro_repo_to_use eq "") {
        OSCAR::PackagePath::use_default_distro_repo ($distro_to_setup);
    } else {
        OSCAR::PackagePath::use_distro_repo ($distro_to_setup,
                                             $distro_repo_to_use);
    }
}

# if ($network) {
#     my $cmd = "$ENV{OSCAR_HOME}/scripts/system-sanity.d/network-check.pl";
#     my $net_config = system($cmd);
#     if ($net_config != 0) {
#         print "Configuration issues detected, configuring the network...\n"
#     }
# }

exit 0;

sub bootstrap () {
    print "OSCAR bootstrap\n";
    # First of all we check if the OSCAR_HOME environment variable is set or not
    # This variable is currently mandatory for the usage of OSCAR.
    if ($ENV{OSCAR_HOME} eq "") {
        use lib cwd() . "/lib"; # case where the script is used from the actual
                                # OSCAR_HOME
        require OSCAR::Env;
        OSCAR::Env::oscar_home_env();
        if ($ENV{OSCAR_HOME} eq "") {
            print "ERROR: Impossible to set OSCAR_HOME.\n";
            return -1;
        }
    }

    # From now we should be able to use some OSCAR modules! :-)

    require OSCAR::Bootstrap;
    my $configurator = OSCAR::Bootstrap::bootstrap_stage0();
    if (!defined $configurator) {
        print "ERROR: Impossible to complete stage 0 of the bootstrap.\n";
        return -1;
    }

    OSCAR::Bootstrap::oscar_bootstrap ($configurator);
}

sub display_list_supported_distros {
    require OSCAR::Distro;
    # We get the list of supported distros
    my $verbose = 1;
    my @distros = OSCAR::Distro::get_list_of_supported_distros ();
    # The command line output is used by other tools so we are careful about
    # displaying only usefull information.
    foreach my $d (@distros) {
        print $d . " ";
    }
    print "\n";
}

sub display_list_setup_distros {
    require OSCAR::PackagePath;
    # We check if one of these distros is setup (i.e. if /tftpboot is correctly
    # populated.
    my @list = OSCAR::PackagePath::get_list_setup_distros ();
    if (!scalar (@list)) {
        print "No distribution is setup for OSCAR\n";
    } else {
        # The output can be used by other tools (such as OSCAR GUIs), we are
        # carefull displaying only the list.
        foreach my $d (@list) {
            print "$d ";
        }
        print "\n";
    }
}

sub help {
    print "Usage: $0 OPTION\n";
    print "\n";
    print "Setup OSCAR for Cluster management.\n";
    print "OPTION can be:\n";
    print " --setup-distro DISTRO_ID: Setup the Linux distribution DISTRO_ID\n"; 
    print "\t(which is one the distribution ids displayed by the\n";
    print "\t--supported-distros option). The repositories used are those\n"; 
    print "\tspecified in the 'supported-distros.xml' file if no\n"; 
    print "\t--mirror-<distro|oscar>-from option is used.\n";
    print " --list-setup-distros: List the Linux distributions that are \n";
    print "\talready setup for OSCAR.\n";
    print " --supported-distros: List the Linux distributions supported by\n";
    print "\tOSCAR.\n";
    print " --display-defaut-distro-repo DISTRO_ID: display the default\n";
    print "\tdistribution repository.\n";
    print " --display-defaut-oscar-repo DISTRO_ID: display the default OSCAR\n";
    print "\trepository.\n";
    print " --use-distro-repo REPO_URL: Use a given repository for OSCAR \n";
    print "\tinstead of the default repository..\n";
    print " --use-oscar-repo REPO_URL: Use a given repository instead of the\n";
    print "\tdefault repository for a given Linux distribution.\n";
    print " --mirror-distro-repo REPO_URL: Mirror a given online repository\n";
    print "\tfor a given Linux distribution.\n";
    print " --mirror-oscar-repo REPO_URL: Mirror a given online OSCAR\n";
    print "\trepository for a given Linux distribution.\n";
#     print " --network.\n";
    print "--bootstrap: Bootstrap OSCAR, i.e., install all the OSCAR\n";
    print "\tprereqs, setup the database, and install and setup everything\n";
    print "\tfor the creation of a OSCAR headnode.\n";
    print " --help: this help information.\n";
    print "\n";
    exit;
}

__END__

=head1 NAME

oscar-config, a command line tool for OSCAR configuration.

=head1 SYNOPSIS

oscar-config OPTIONS

=head1 DESCRIPTION

oscar-config is a command line tool for OSCAR configuration, from OSCAR
bootstrapping to repository configuration. It also allow users to get 
information about the current OSCAR configuration.

=head1 SYNTAX

setup_pxe [options]

=head1 OPTIONS

Recognized options include:

=over 11

=item --setup-distro <DISTRO_ID>

Setup the Linux distribution DISTRO_ID (which is one the distribution ids
displayed by the --supported-distros option). The repositories used are those
specified in the 'supported-distros.xml' file if no --mirror-<distro|oscar>-from
option is used.

=item --list-setup-distros

List the Linux distributions that are already setup for OSCAR.

=item --supported-distros

List the Linux distributions supported by OSCAR.

=item --display-defaut-distro-repo <DISTRO_ID>

Display the default distribution repository.

=item --display-defaut-oscar-repo <DISTRO_ID>

Display the default OSCAR repository.

=item --use-distro-repo <REPO_URL>

Use a given repository instead of the default repository for a given Linux
distribution.

=item --use-oscar-repo <REPO_URL>

Use a given repository for OSCAR instead of the default repository.

=item --mirror-distro-repo <REPO_URL>

Mirror a given online repository for a given Linux distribution.

=item --mirror-oscar-repo <REPO_URL>

Mirror a given online OSCAR repository for a given Linux distribution.

=item --bootstrap

Bootstrap OSCAR, i.e., install all the OSCAR prereqs, setup the database, and
install and setup everything for the creation of a OSCAR headnode.

=item --help

This help information.

=back

=head1 AUTHOR

Geoffroy Vallee <valleegr@ornl.gov>

=head1 SEE ALSO

perl(1)

=cut
