#!/usr/bin/perl

#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
 
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#   This script is designed to be run after the image is built.
#   It will do all the fixups required.

use strict;
use lib "$ENV{OSCAR_HOME}/lib",'/usr/lib/systeminstaller';
use Carp;
use File::Copy;
use File::Path;
use File::Basename;
use SIS::Image;
use OSCAR::Package;
use Data::Dumper;

!system("./allow_client_access") or croak("Couldn't run client access program");

push_hosts() or croak("Couldn't push hosts file to images");

my @pkgs = list_pkg();

foreach my $pkg (@pkgs) {
	run_pkg_script($pkg,"post_clients",1) or croak("Couldn't run post_clients script for $pkg");
}

sub push_hosts {
    my @images = imageList();
    foreach my $image (@images) {
        my $dir = $image->{PATH};
        copy("/etc/hosts","$dir/etc/hosts") or (carp "Can't copy /etc/hosts to $dir",
                                                return undef);
    }
    return 1;
}

