#!/usr/bin/perl -w

use strict;
use lib "$ENV{OSCAR_HOME}/lib", "../lib"; 
use Carp;

# all the rpms we KNOW we installed

my @rpms = qw(
              c3
              pfilter
              lam
	      modules
	      switcher
              pvm
              openpbs-oscar 
              openpbs-oscar-mom
              openpbs-oscar-server
              openpbs-oscar-gui
              openpbs-oscar-commands
              lam-profile-d-6.5.6-usysv.1oscar
              sync-users-oscar
              maui-oscar
              libdbdcsv-perl
              libappconfig-perl
              systeminstaller
              systeminstaller-x11
              systemconfigurator
              systemimager-server
              systemimager-common
              systemimager-client
              systemimager-i386boot
              systemimager-ia64boot
	      mpich
             );

stop_services();

# Delete the clients first so /etc/hosts gets cleaned
print "/usr/bin/mksimachine --Delete --all\n";
system("/usr/bin/mksimachine --Delete --all");

uninstall_rpms("lam-module"); # Don't know why this doesn't work with the others

uninstall_rpms(@rpms);

delete_from_pool(@rpms);

cleanup_files();

delete_oscar_users();

sub delete_oscar_users {
    my @oscar_users = qw(
                   oscartst
                  );
    foreach my $oscar_user (@oscar_users) {
        print "Removing user $oscar_user\n";
        system("userdel -r $oscar_user");
    }
}


sub stop_services {
    my @services = qw(
                      systemimager
                      dhcpd
                      pbs_server
                     );
    foreach my $service (@services) {
        print "service $service stop\n";
        system("service $service stop");
    }
}

sub cleanup_files {
    my @dirs = qw(
                  /usr/spool/PBS
                  /usr/local/pbs
                  /usr/local/maui
                  /var/log/systemimager
                  /var/lib/clamdr
                  /var/lib/systeminstaller
                  /usr/local/lib/systemimager
		  /etc/systemimager
                  /etc/dhcpd.conf
                  /etc/profile.d/mpi-00mpich.csh
                  /etc/profile.d/mpi-00mpich.sh
                  /etc/profile.d/mpi-01lam.csh
                  /etc/profile.d/mpi-01lam.sh
                 );
    foreach my $file (@dirs) {
	print "rm -rf $file \n";
        system("rm -rf $file");
    }
}


print "rm -rf /var/lib/clamdr\n";
system("rm -rf /var/lib/clamdr");

print "rm -rf /var/lib/systemimager\n";
system("rm -rf /var/lib/systemimager");

print "rm -f /etc/cron.daily/synctime.sh\n";     # tjn 1/18/02
system("rm -f /etc/cron.daily/synctime.sh");



sub delete_from_pool {
    my @rpms = @_;
    my $dir = "/tftpboot/rpm/";
    
    foreach my $rpm (@rpms) {
        print "rm -f $dir$rpm*\n";
        system("rm -f $dir$rpm*");
    }
}

sub uninstall_rpms {
    my @rpms = @_;
    my @deleteme = ();
    foreach my $rpm (@rpms) {
        if(_is_installed($rpm)) {
            push @deleteme, $rpm;
        }
    }
    if(scalar(@deleteme)) {
        my $rpmcmd = 'rpm -e --allmatches --nodeps ' . (join ' ', @deleteme);
	print "$rpmcmd\n";
        !system($rpmcmd) or croak "couldn't uninstall the rpms";
    }
   return 1;
}

sub _is_installed {
    my $rpm = shift;
    return !system("rpm -q $rpm");
}
