#!/usr/bin/env perl

# Copyright (c) 2002 The Trustees of Indiana University.  
#                    All rights reserved.
# 
# This file is part of the OSCAR software package.  For license
# information, see the COPYING file in the top level directory of the
# OSCAR source distribution.
#
# $Id: setup,v 1.2 2003/07/23 15:58:52 brechin Exp $
#

use strict;
use lib "$ENV{OSCAR_HOME}/lib";
use OSCAR::Logger;
use Carp;
use OSCAR::Distro;

# Version included in media directory

my $ver = "3.14";
my $real_name = "HTML-Tree";
my $module_name = "HTML::Tree";
my ( $distn, $distv ) = which_distro_server();

if ( $distn eq 'mandrake' ) {
  if ( system("rpm --quiet -q perl-devel") != 0 ) {
    !system("rpm -Uvh /tftpboot/rpm/perl-devel-*.rpm") || croak "Couldn't install perl-devel!";
  }
}


# Helper subroutine

sub do_run {
    my $cmd = join(' ', @_);
    if (system($cmd) != 0) {
	croak("Not able to execute: $cmd");
    }
}

# See if we need to install the perl module

oscar_log_subsection("Checking to see if we need to install $module_name");
my $eval_str = "{ require $module_name }";
eval $eval_str;
if ($@) {
    oscar_log_subsection("$module_name is not yet installed");

    my $topdir = "$ENV{OSCAR_HOME}/share/prereqs/$real_name";
    my $tarball = "$topdir/media/$real_name-$ver.tar.gz";
    my $tempdir = "/tmp/oscar-install-$real_name.$$";

    mkdir($tempdir) or carp("Can't create temp dir: $tempdir");
    chomp(my $pwd = `pwd`);
    chdir($tempdir);

    do_run("tar zxf $tarball");
    croak("Not able to chdir($real_name-$ver)")
	if (!chdir("$real_name-$ver"));
    do_run("perl Makefile.PL");
    do_run("make all");
    do_run("make install");

    oscar_log_subsection("$module_name installed successfully");

    chdir($pwd);
    system("rm -rf $tempdir");
} 

# It's already installed -- nothing to do

else {
    oscar_log_subsection("$module_name appears to be installed already");
}

# All done

0;
