#!/usr/bin/env perl

# Copyright (c) 2003, NEC HPC Europe, Erich Focht
#                     All rights reserved.


use lib "$ENV{OSCAR_HOME}/lib";
use OSCAR::Logger;
use Carp;
use OSCAR::Distro;
use OSCAR::PackageBest;

my $rpmdir = "/tftpboot/rpm";
my ($name, $ver) = which_distro_server();
my $arch = `uname -i`;
chomp $arch;

if ($arch eq "x86_64") {
  oscar_log_subsection("Checking for syslinux, it needs to be forced on x86_64\n");
  if ($name eq "redhat" || $name eq "fedora") {
    if (system("rpm -q syslinux >/dev/null 2>&1")) {
      install_rpm("syslinux","i386");
    }
  }
}

sub install_rpm {
  my ($name,$arch) = @_;
  opendir(DIR, "$rpmdir") || croak("Can't open $rpmdir for syslinux");
  my @rpms = grep /^$name-[\d+].*\.$arch\.rpm$/, readdir(DIR);
  closedir DIR;
  if (@rpms) {
    my $pkg = $rpmdir . "/" . OSCAR::PackageBest::find_best(@rpms);
    if (!system("rpm -Uhv $pkg >/dev/null 2>&1")) {
      oscar_log_subsection("...installed RPM $pkg\n");
    } else {
      carp("Installation of $pkg failed!\n");
      return 1;
    }
  } else {
    oscar_log_subsection("WARNING: no RPM found for $name!\n");
  }
  return 0;
}
exit(0);
