#!/usr/bin/env perl
#
# Copyright (c) 2009 Oak Ridge National Laboratory
#                    Geoffroy Vallee <valleegr@ornl.gov>
#                    All rights reserved.
#
# This file is part of the OSCAR software package.  For license
# information, see the COPYING file in the top level directory of the
# OSCAR source distribution.
#
# $Id$
#

use strict;
use Carp;

use OSCAR::PackagePath;

# We get the list of all distros that are set up and for each of them,
# we reconfigure them (that allows us to update the config files in /tftpboot).
my @list = OSCAR::PackagePath::get_list_setup_distros ();

foreach my $distro (@list) {
    # TODO: put the code to setup a distro in a library rather than execute the
    # oscar-config command
    my $cmd = "/usr/bin/oscar-config --setup-distro $distro";
    if (system ($cmd)) {
        die "ERROR: Impossible to execute $cmd";
    }
}

exit 0;

