#!/bin/csh
#
# $Id: build-notes,v 1.5 2002/09/11 01:26:33 jsquyres Exp $
#
# $COPYRIGHT$
#

# Look in ../packages/* for doc/install.tex files.  When we find those
# files, add them to install-notes.tex.

\cp -f notes.tex.in notes.tex

# Don't use a glob here, because this directly affects the ordering of
# sections in the output doc.  So pipe the output of ls here though
# sort so that we can have deterministic ordering of the sections.

foreach file (`/bin/ls ../../packages/*/doc/install.tex | sort`)
    set dir="`dirname $file`"
    set dir="`dirname $dir`"
    if (! -f $dir/.oscar_ignore) then
	echo "\input{$file}" >> notes.tex
    endif
end
